package langdetect

import (
	"encoding/json"
	"sync"
)

var (
	embeddedCountryLocaleMap map[string]string
	embeddedOnce             sync.Once
)

// 内嵌的JSON数据
const countryLocaleJSON = `{
  "AD": "cat",       
  "AE": "ara",       
  "AF": "pus",        
  "AG": "en",        
  "AI": "en",        
  "AL": "alb",        
  "AM": "arm",       
  "AO": "pt",       
  "AR": "spa",        
  "AS": "en",        
  "AT": "de",       
  "AU": "en",       
  "AW": "nl", 
  "AX": "swe",       
  "AZ": "aze",      
  "BA": "bos",      
  "BB": "en",       
  "BD": "ben",   
  "BE": "nl",
  "BF": "fra",      
  "BG": "bul",      
  "BH": "ara",      
  "BI": "run",      
  "BJ": "fra",      
  "BL": "fra",      
  "BM": "en",      
  "BN": "may",      
  "BO": "spa",      
  "BQ": "nl",      
  "BR": "pt",      
  "BS": "en",      
  "BT": "dzo",      
  "BW": "en",      
  "BY": "bel",      
  "BZ": "en",      
  "CA": "en",      
  "CD": "fra",      
  "CF": "fra",      
  "CG": "fra",      
  "CH": "de",      
  "CI": "fra",      
  "CK": "en",      
  "CL": "spa",      
  "CM": "fra",      
  "CN": "zh",      
  "CO": "spa",      
  "CR": "spa",      
  "CU": "spa",      
  "CV": "pt", 
  "CW": "nl",     
  "CY": "el",     
  "CZ": "cs",     
  "DE": "de",     
  "DJ": "ara",     
  "DK": "dan",     
  "DM": "en",     
  "DO": "spa",     
  "DZ": "ara",     
  "EC": "spa",     
  "EE": "est",     
  "EG": "ara",     
  "EH": "ara",     
  "ER": "tir",     
  "ES": "spa",     
  "ET": "amh",     
  "FI": "fin",     
  "FJ": "fij",     
  "FK": "en",     
  "FM": "en",     
  "FO": "fao",     
  "FR": "fra",     
  "GA": "fra",     
  "GB": "en",     
  "GD": "en",     
  "GE": "geo",     
  "GF": "fra",     
  "GG": "en",     
  "GH": "aka",     
  "GI": "en",
  "GL": "kal",
  "GM": "en",
  "GN": "fra",
  "GP": "fra",
  "GQ": "spa",
  "GR": "el",
  "GT": "spa",
  "GU": "en",
  "GW": "pt",
  "GY": "en",
  "HK": "yue",
  "HN": "spa",
  "HR": "hrv",
  "HT": "fra",
  "HU": "hu",
  "ID": "id",
  "IE": "en",
  "IL": "heb",
  "IM": "en",
  "IN": "hi",
  "IQ": "ara",
  "IR": "per",
  "IS": "ice",
  "IT": "it",
  "JE": "en",
  "JM": "en",
  "JO": "ara",
  "JP": "jp",
  "KE": "swa",
  "KG": "kir",
  "KH": "hkm",     
  "KI": "en",     
  "KM": "ara",     
  "KN": "en",     
  "KP": "kor",     
  "KR": "kor",     
  "KW": "ara",     
  "KY": "en",     
  "KZ": "kaz",     
  "LA": "lao",     
  "LB": "ara",     
  "LC": "en",     
  "LI": "de",     
  "LK": "sin",     
  "LR": "en",     
  "LS": "en",     
  "LT": "lit",     
  "LU": "ltz",     
  "LV": "lav",     
  "LY": "ara",     
  "MA": "ara",     
  "MC": "fra",     
  "MD": "rom",     
  "ME": "src",     
  "MF": "fra",     
  "MG": "mg",     
  "MH": "en",     
  "MK": "mac",     
  "ML": "fra",     
  "MM": "bur",
  "MN": "mon",   
  "MO": "zh",   
  "MP": "en",   
  "MQ": "fra",   
  "MR": "ara",   
  "MS": "en",   
  "MT": "mlt",   
  "MU": "mau",  
  "MV": "div",   
  "MW": "nya",   
  "MX": "spa",   
  "MY": "may",   
  "MZ": "pt",   
  "NA": "en",   
  "NC": "fra",   
  "NE": "fra",   
  "NF": "en",   
  "NG": "en",   
  "NI": "spa",   
  "NL": "nl",   
  "NO": "nob",   
  "NP": "nep",   
  "NR": "nau",   
  "NU": "en",   
  "NZ": "en",   
  "OM": "ara",   
  "PA": "spa",   
  "PE": "spa",   
  "PF": "fra",   
  "PG": "tpi",
  "PH": "fil",   
  "PK": "urd",    
  "PL": "pl",    
  "PM": "fra",    
  "PN": "en",    
  "PR": "spa",    
  "PS": "ara",    
  "PT": "pt",    
  "PW": "pau",   
  "PY": "spa",    
  "QA": "ara",    
  "RE": "fra",    
  "RO": "rom",    
  "RS": "src",    
  "RU": "ru",    
  "RW": "kin",    
  "SA": "ara",    
  "SB": "en",    
  "SC": "fra",    
  "SD": "ara",    
  "SE": "swe",    
  "SG": "en",    
  "SH": "en",    
  "SI": "slo",    
  "SJ": "nob",    
  "SK": "sk",    
  "SL": "en",    
  "SM": "it",    
  "SN": "fra",    
  "SO": "som",
  "SR": "nl",
  "SS": "en",
  "ST": "pt",
  "SV": "spa",
  "SX": "nl",
  "SY": "ara",
  "SZ": "en",
  "TC": "en",
  "TD": "fra",
  "TG": "fra",
  "TH": "th",
  "TJ": "tgk",
  "TK": "en",
  "TL": "pt",
  "TM": "tuk",
  "TN": "ara",
  "TO": "ton",
  "TR": "tr",
  "TT": "en",
  "TV": "en",
  "TW": "cht",
  "TZ": "swa",
  "UA": "ukr",
  "UG": "en",
  "US": "en",
  "UY": "spa",
  "UZ": "uzb",
  "VA": "it",
  "VC": "en",
  "VE": "spa",
  "VG": "en",
  "VI": "en",
  "VN": "vie",
  "VU": "bis",
  "WF": "fra",
  "WS": "sm",
  "YE": "ara",
  "YT": "fra",
  "ZA": "zul",
  "ZM": "en",
  "ZW": "sna"
}`

// LoadEmbeddedCountryLocaleMap 加载内嵌的国家代码到语言环境的映射
func LoadEmbeddedCountryLocaleMap() (map[string]string, error) {
	var err error
	embeddedOnce.Do(func() {
		// 解析内嵌的JSON字符串
		err = json.Unmarshal([]byte(countryLocaleJSON), &embeddedCountryLocaleMap)
	})

	return embeddedCountryLocaleMap, err
}

// GetEmbeddedLocaleByCountryCode 根据国家代码获取语言环境（使用内嵌数据）
func GetEmbeddedLocaleByCountryCode(countryCode string) (string, bool) {
	if embeddedCountryLocaleMap == nil {
		_, err := LoadEmbeddedCountryLocaleMap()
		if err != nil {
			return "", false
		}
	}

	locale, exists := embeddedCountryLocaleMap[countryCode]
	return locale, exists
}
